"""add_channel_post_products_association_table

Revision ID: 3e1bcbd7f157
Revises: 0a1b2c3d4e5f
Create Date: 2026-07-20 16:31:46.650704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1bcbd7f157'
down_revision = '0a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
