"""Add smart pricing and discount analytics columns

Revision ID: ad44106346be
Revises: fe7e7d1f4b22
Create Date: 2026-07-16 19:01:49.544446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad44106346be'
down_revision = 'fe7e7d1f4b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_discount_min_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='2500.00'))
        batch_op.add_column(sa.Column('qty_discount_open_to_all', sa.Boolean(), nullable=False, server_default='true'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spending_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('qty_discount_amount_saved', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_price_enabled', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('smart_price_adjustment_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('smart_price_adjustment_pct')
        batch_op.drop_column('smart_price_enabled')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('qty_discount_amount_saved')
        batch_op.drop_column('spending_discount_amount')

    with op.batch_alter_table('loyalty_settings', schema=None) as batch_op:
        batch_op.drop_column('qty_discount_open_to_all')
        batch_op.drop_column('qty_discount_min_price')

    # ### end Alembic commands ###
