"""Init db and add loyalty system

Revision ID: f0025676c6cf
Revises: 
Create Date: 2026-07-02 11:31:20.835164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0025676c6cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reward_earned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_level_id_after', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lifetime_total_after', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_items', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_loyalty_level', 'loyalty_levels', ['loyalty_level_id_after'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_hidden', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('min_loyalty_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_min_loyalty_level', 'loyalty_levels', ['min_loyalty_level_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_level_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_status', sa.Enum('new', 'active', 'loyal', 'vip', 'elite', name='customerstatus'), nullable=False, server_default='new'))
        batch_op.add_column(sa.Column('loyalty_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reward_points', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('lifetime_points_earned', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_money_spent', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('lifetime_savings', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_items_purchased', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('first_purchase_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_purchase_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('referred_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_loyalty_level_id'), ['loyalty_level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key('fk_users_loyalty_level', 'loyalty_levels', ['loyalty_level_id'], ['id'])
        batch_op.create_foreign_key('fk_users_referred_by', 'users', ['referred_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_loyalty_level_id'))
        batch_op.drop_column('referred_by_user_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('last_purchase_date')
        batch_op.drop_column('first_purchase_date')
        batch_op.drop_column('total_items_purchased')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('lifetime_savings')
        batch_op.drop_column('total_money_spent')
        batch_op.drop_column('lifetime_points_earned')
        batch_op.drop_column('reward_points')
        batch_op.drop_column('loyalty_score')
        batch_op.drop_column('customer_status')
        batch_op.drop_column('loyalty_level_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('min_loyalty_level_id')
        batch_op.drop_column('price_hidden')
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total_items')
        batch_op.drop_column('lifetime_total_after')
        batch_op.drop_column('loyalty_level_id_after')
        batch_op.drop_column('reward_earned')
        batch_op.drop_column('savings_amount')

    # ### end Alembic commands ###
